# Generated by Django 6.0.6 on 2026-08-24 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Account that last saved this grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
