# Generated by Django 6.0.6 on 2026-08-26 18:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backfill_grade_assigned_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-date_assigned', 'kind']},
        ),
        migrations.AddField(
            model_name='grade',
            name='kind',
            field=models.CharField(choices=[('coursework', 'Coursework'), ('midterm', 'Midterm'), ('final', 'Final exam'), ('retake', 'Retake')], default='final', help_text='Which part of the course this mark is for', max_length=12),
        ),
        migrations.AddField(
            model_name='grade',
            name='weight',
            field=models.PositiveIntegerField(default=100, help_text='How much this component counts towards the course mark', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.enrollment'),
        ),
    ]
