name: Keep Render Awake
on:
  schedule:
      - cron: "*/10 * * * *"
        workflow_dispatch:
        jobs:
          ping:
              runs-on: ubuntu-latest
                  steps:
                        - name: Ping Render Site
                                run: curl -sSf https://diploma-project-sms-management-system.onrender.com > /dev/null
